export const business = {
  name: "Reparaciones Nieto",
  siteUrl: "https://persianas-y-fontaneria.com",
  phone: "623 15 90 10",
  phoneFormatted: "+34 623 15 90 10",
  whatsapp: "34623159010",
  address: "Calle del Dr. Bergez, 16, 03012 Alicante",
  email: "edisonnietoceferino@gmail.com",
  hours: "Abierto 24 horas",
  experience: "15 años de experiencia",
  logo: "/Logo.png",
  teamImage: "/Team-Nieto.jpeg",
  heroImage: "/reparaciones-nieto-instalaciones-1.jpeg",
  geo: {
    latitude: 38.3567293,
    longitude: -0.4804119,
  },
  mapsUrl: "https://www.google.com/maps?cid=14559646464534534534",
  mapsEmbedUrl:
    "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3128.665248900112!2d-0.48041190000000006!3d38.3567293!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x49e53b2f37cc333b%3A0xca0e26e43f43d3b2!2sReparaciones%20Nieto%20-%20Fontanero%20Alicante!5e0!3m2!1sen!2ses!4v1776090518412!5m2!1sen!2ses",
  areas: ["Alicante", "Elche", "Benidorm", "El Campello", "San Juan", "Mutxamel", "San Vicente del Raspeig", "Santomera", "La Manga"],
  areaImages: {
    "alicante": "/reparaciones-nieto-instalaciones-1.jpeg",
    "elche": "/reparaciones-nieto-instalaciones-2.jpeg",
    "benidorm": "/reparaciones-nieto-instalaciones-3.jpeg",
    "el-campello": "/reparaciones-nieto-instalaciones-4.jpeg",
    "san-juan": "/reparaciones-nieto-instalaciones-5.jpeg",
    "mutxamel": "/Pintura-reparaciones-nieto.jpeg",
    "san-vicente-del-raspeig": "/fontaneria-reparaciones-nieto.jpeg",
    "santomera": "/Cierre-metal.jpeg",
    "la-manga": "/reparaciones-nieto-instalaciones-3.jpeg",
  } as Record<string, string>,
  galleryImages: [
    { src: "/reparaciones-nieto-instalaciones-1.jpeg", alt: "Instalación realizada por Reparaciones Nieto en Alicante" },
    { src: "/reparaciones-nieto-instalaciones-2.jpeg", alt: "Detalle de trabajo de persianas de Reparaciones Nieto" },
    { src: "/reparaciones-nieto-instalaciones-3.jpeg", alt: "Servicio técnico de Reparaciones Nieto en vivienda" },
    { src: "/reparaciones-nieto-instalaciones-4.jpeg", alt: "Trabajo terminado de Reparaciones Nieto" },
    { src: "/reparaciones-nieto-instalaciones-5.jpeg", alt: "Reparación e instalación completada por Reparaciones Nieto" },
    { src: "/fontaneria-reparaciones-nieto.jpeg", alt: "Trabajo de fontanería de Reparaciones Nieto" },
    { src: "/Cierre-metal.jpeg", alt: "Cierre metálico instalado o reparado por Reparaciones Nieto" },
    { src: "/Pintura-reparaciones-nieto.jpeg", alt: "Intervención técnica de Reparaciones Nieto" },
    { src: "/Team-Nieto.jpeg", alt: "Equipo de Reparaciones Nieto" },
  ],
  services: [
    {
      id: "persianas",
      title: "Reparación de Persianas",
      description: "Servicio profesional de reparación e instalación de persianas de todo tipo.",
      slug: "persianas",
      icon: "Settings",
      image: "/reparaciones-nieto-instalaciones-1.jpeg",
      subservices: [
        "Cambio de cintas y recogedores",
        "Sustitución de lamas dañadas",
        "Reparación de ejes y poleas",
        "Persianas atascadas o descolgadas",
      ],
    },
    {
      id: "persianas-hogar",
      title: "Persianas de Hogar",
      description: "Instalación y reparación de persianas domésticas, térmicas y de seguridad.",
      slug: "persianas-hogar",
      icon: "Home",
      image: "/reparaciones-nieto-instalaciones-2.jpeg",
      subservices: [
        "Persianas de aluminio térmico",
        "Motorización para vivienda",
        "Aislamiento y confort",
        "Revisión de cajones y guías",
      ],
    },
    {
      id: "persianas-local",
      title: "Persianas de Local",
      description: "Soluciones para comercios y locales: persianas enrollables y de seguridad.",
      slug: "persianas-local",
      icon: "Store",
      image: "/reparaciones-nieto-instalaciones-3.jpeg",
      subservices: [
        "Persianas comerciales enrollables",
        "Aperturas urgentes de local",
        "Cerraduras y seguridad",
        "Motores y mandos",
      ],
    },
    {
      id: "cierres-metalicos",
      title: "Cierres Metálicos",
      description: "Especialistas en cierres metálicos para negocios y naves industriales.",
      slug: "cierres-metalicos",
      icon: "Lock",
      image: "/Cierre-metal.jpeg",
      subservices: [
        "Cierres motorizados",
        "Reparación de lamas y ejes",
        "Mantenimiento preventivo",
        "Candados y refuerzo de seguridad",
      ],
    },
    {
      id: "fontaneria",
      title: "Fontanería",
      description: "Fontanero urgente en Alicante para averías, fugas e instalaciones.",
      slug: "fontaneria",
      seoTitle: "Fontanería General en Alicante",
      seoDescription: "Servicio general de fontanería en Alicante para averías, instalaciones, revisiones y mantenimiento con atención rápida y presupuesto claro.",
      icon: "Droplets",
      image: "/fontaneria-reparaciones-nieto.jpeg",
      subservices: [
        "Fontanero urgente",
        "Atascos de desagües, fregadero y WC",
        "Fugas de agua",
        "Baja presión de agua",
        "Grifos que gotean",
        "Problemas con calentador y agua caliente",
        "Cisterna y WC averiado",
      ],
    }
    ,
    {
      id: "fontanero-urgente",
      title: "Fontanero Urgente",
      description: "Atención rápida para incidencias de fontanería urgentes en Alicante.",
      slug: "fontanero-urgente",
      seoTitle: "Fontanero Urgente en Alicante",
      seoDescription: "Atención urgente de fontanería en Alicante para fugas, reboses, averías imprevistas y problemas que no pueden esperar.",
      icon: "Droplets",
      image: "/fontaneria-reparaciones-nieto.jpeg",
      parentServiceId: "fontaneria",
    },
    {
      id: "atascos",
      title: "Atascos de Desagües, Fregadero y WC",
      description: "Desatascos rápidos y profesionales en cocina, baño, WC y bajantes interiores.",
      slug: "atascos-desagues-fregadero-wc",
      seoTitle: "Desatascos de Desagües, Fregadero y WC en Alicante",
      seoDescription: "Desatascos en Alicante para fregaderos, desagües y WC con diagnóstico del origen y solución profesional.",
      icon: "Droplets",
      image: "/fontaneria-reparaciones-nieto.jpeg",
      parentServiceId: "fontaneria",
    },
    {
      id: "fugas-agua",
      title: "Fugas de Agua",
      description: "Localización y reparación de fugas de agua en viviendas y locales en Alicante.",
      slug: "fugas-de-agua",
      seoTitle: "Reparación de Fugas de Agua en Alicante",
      seoDescription: "Localización y reparación de fugas de agua en Alicante para viviendas, baños, cocinas y locales comerciales.",
      icon: "Droplets",
      image: "/fontaneria-reparaciones-nieto.jpeg",
      parentServiceId: "fontaneria",
    },
    {
      id: "baja-presion",
      title: "Baja Presión de Agua",
      description: "Diagnóstico y solución de problemas de baja presión en grifos y circuitos domésticos.",
      slug: "baja-presion-agua",
      seoTitle: "Problemas de Baja Presión de Agua en Alicante",
      seoDescription: "Solucionamos baja presión de agua en Alicante revisando grifos, llaves, filtros, cal y rendimiento del circuito.",
      icon: "Droplets",
      image: "/fontaneria-reparaciones-nieto.jpeg",
      parentServiceId: "fontaneria",
    },
    {
      id: "grifos-gotean",
      title: "Grifos que Gotean",
      description: "Reparación y sustitución de grifos con pérdidas, goteos o cierre defectuoso.",
      slug: "grifos-que-gotean",
      seoTitle: "Reparación de Grifos que Gotean en Alicante",
      seoDescription: "Reparación de grifos que gotean en Alicante, con revisión de cierres, cartuchos, juntas y pérdidas de agua.",
      icon: "Droplets",
      image: "/fontaneria-reparaciones-nieto.jpeg",
      parentServiceId: "fontaneria",
    },
    {
      id: "calentador-agua-caliente",
      title: "Problemas con Calentador y Agua Caliente",
      description: "Solucionamos fallos de calentador, termo y falta de agua caliente en Alicante.",
      slug: "problemas-calentador-agua-caliente",
      seoTitle: "Problemas con Calentador y Agua Caliente en Alicante",
      seoDescription: "Revisión y solución de fallos de calentador, termo y agua caliente en Alicante con diagnóstico técnico.",
      icon: "Droplets",
      image: "/fontaneria-reparaciones-nieto.jpeg",
      parentServiceId: "fontaneria",
    },
    {
      id: "cisterna-wc",
      title: "Cisterna y WC Averiado",
      description: "Reparación de cisternas, mecanismos de descarga y averías frecuentes en WC.",
      slug: "cisterna-wc-averiado",
      seoTitle: "Reparación de Cisterna y WC Averiado en Alicante",
      seoDescription: "Reparación de cisternas y WC averiados en Alicante, incluyendo mecanismos de descarga, llenado y pérdidas.",
      icon: "Droplets",
      image: "/fontaneria-reparaciones-nieto.jpeg",
      parentServiceId: "fontaneria",
    }
  ]
};
